<?php
session_start();

// Ensure the user is logged in and is a System Admin
if (!isset($_SESSION['user_id']) || $_SESSION['role'] != 'System Admin') {
    header("Location: loginpage.php");
    exit();
}

require 'db_connect.php';

// Function to fetch reports (example)
function getReports($conn) {
    $reports = [];
    $sql = "SELECT * FROM reports ORDER BY generated_at DESC";
    $result = $conn->query($sql);
    if ($result->num_rows > 0) {
        while ($row = $result->fetch_assoc()) {
            $reports[] = $row;
        }
    }
    return $reports;
}

$reports = getReports($conn);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 50px;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: #800000;
            padding: 30px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            color: #fff;
        }
        
        h1 {
            text-align: center;
            margin-bottom: 50px;
        }
        
        .report {
            background-color: #fff;
            color: #000;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <h1>Reports</h1>
    <div class="container">
        <?php foreach ($reports as $report): ?>
            <div class="report">
                <strong><?php echo $report['generated_at']; ?>:</strong>
                <h2><?php echo htmlspecialchars($report['report_name']); ?></h2>
                <p>Generated by: <?php echo htmlspecialchars($report['generated_by']); ?></p>
                <p><?php echo htmlspecialchars($report['report_data']); ?></p>
            </div>
        <?php endforeach; ?>
    </div>
</body>
</html>
